# Generated by Django 2.0.2 on 2018-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_regularuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
