# Generated by Django 2.0.2 on 2018-06-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_regularuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='referral',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
