# Generated by Django 2.0.2 on 2018-06-04 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_regularuser_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
