# Generated by Django 2.0.2 on 2018-06-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20180604_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularuser',
            name='check',
        ),
    ]
