# Generated by Django 2.0.2 on 2018-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_regularuser_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('prize', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('points', models.IntegerField(null=True)),
            ],
        ),
    ]
