# Generated by Django 2.0.2 on 2018-07-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
