# Generated by Django 2.0.2 on 2018-07-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20180719_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='event_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_user',
        ),
        migrations.DeleteModel(
            name='EventUser',
        ),
    ]
