# Generated by Django 2.0.2 on 2018-07-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20180719_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='subscription_amount',
            field=models.IntegerField(default=0),
        ),
    ]
