# Generated by Django 2.0.2 on 2018-07-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_auto_20180719_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='payment_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
