# Generated by Django 2.0.2 on 2018-07-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_auto_20180720_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='regularuser',
            name='event',
            field=models.ManyToManyField(to='user_app.Event'),
        ),
    ]
