# Generated by Django 2.0.2 on 2018-07-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_auto_20180720_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='referral',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
