# Generated by Django 2.0.2 on 2018-07-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_auto_20180720_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
