# Generated by Django 2.0.2 on 2018-07-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_auto_20180720_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='user_app.Event'),
        ),
    ]
