# Generated by Django 2.0.2 on 2018-07-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_auto_20180720_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='regular_user',
        ),
        migrations.AddField(
            model_name='regularuser',
            name='event',
            field=models.ManyToManyField(blank=True, to='user_app.Event'),
        ),
    ]
