# Generated by Django 2.0.2 on 2018-07-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_auto_20180720_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='total_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
