# Generated by Django 2.0.2 on 2018-07-27 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0025_userverification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVerification',
            new_name='VerifiedUser',
        ),
    ]
