# Generated by Django 2.0.2 on 2018-08-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_regularuser_fb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.Event'),
        ),
    ]
