# Generated by Django 2.0.2 on 2018-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_file_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='suggested_referral',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
