# Generated by Django 2.0.2 on 2018-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_regularuser_suggested_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='fb_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
