# Generated by Django 2.0.6 on 2018-08-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_auto_20180805_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
